name: CI

on:
  push:
    branches: [main, "version-*"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run typecheck
      - run: bun run typecheck:examples
      - run: bun test
      - run: bun run docs:build
